#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NFCFighters.Resource", IsApplication=true)]

namespace NFCFighters
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070001
			public const int notificationContent = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int notificationTitle = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backarrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backg_button1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backg_button2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backg_button3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int backgr_land = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int backgr_land_day = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int backgr_port = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int backgr_port_day = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int exit = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logo = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int multiplayer = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int play = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int settings = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int singleplayer = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080016
			public const int bSetSave = 2131230742;
			
			// aapt resource value: 0x7f080009
			public const int buttonBack = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int buttonExit = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int buttonMP = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int buttonPlay = 2131230724;
			
			// aapt resource value: 0x7f080007
			public const int buttonSP = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int buttonSettings = 2131230725;
			
			// aapt resource value: 0x7f08000d
			public const int cbInvert = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int color = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int color1 = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int color2 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int color3 = 2131230738;
			
			// aapt resource value: 0x7f080002
			public const int imgLogo = 2131230722;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout = 2131230731;
			
			// aapt resource value: 0x7f080001
			public const int linearLayout1 = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int linearLayout2 = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int mainLayout = 2131230720;
			
			// aapt resource value: 0x7f080013
			public const int nightmode = 2131230739;
			
			// aapt resource value: 0x7f080015
			public const int notifications = 2131230741;
			
			// aapt resource value: 0x7f08000a
			public const int scrollView = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int setDivider = 2131230734;
			
			// aapt resource value: 0x7f08000c
			public const int textView1 = 2131230732;
			
			// aapt resource value: 0x7f080014
			public const int textView2 = 2131230740;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Play = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Settings = 2130968578;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f060000
			public const int numberOfClicks = 2131099648;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int accessibility = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int back = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int colorblind = 2131034119;
			
			// aapt resource value: 0x7f05000f
			public const int colorselection = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int configok = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int doexit = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int exit = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int invert = 2131034118;
			
			// aapt resource value: 0x7f050012
			public const int multiplayer = 2131034130;
			
			// aapt resource value: 0x7f050010
			public const int nightmode = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int no = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int notifications = 2131034132;
			
			// aapt resource value: 0x7f05000b
			public const int ok = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int play = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int restart = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int save = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int savesuccess = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int settings = 2131034114;
			
			// aapt resource value: 0x7f050011
			public const int singleplayer = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int yes = 2131034124;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
