#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NFCFighters.Resource", IsApplication=true)]

namespace NFCFighters
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backgr_land = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backgr_port = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000c
			public const int bSetSave = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int buttonExit = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int buttonOptions = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int buttonPlay = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int cbSetColorBlind = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int cbSetLeftHanded = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout2 = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int mainLayout = 2131165184;
			
			// aapt resource value: 0x7f070006
			public const int scrollView = 2131165190;
			
			// aapt resource value: 0x7f07000b
			public const int setDivider = 2131165195;
			
			// aapt resource value: 0x7f070008
			public const int textView1 = 2131165192;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Settings = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Plurals
		{
			
			// aapt resource value: 0x7f060000
			public const int numberOfClicks = 2131099648;
			
			static Plurals()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Plurals()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050005
			public const int accessibility = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int colorblind = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int configok = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int doexit = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int exit = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int lefthanded = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int no = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int ok = 2131034123;
			
			// aapt resource value: 0x7f050002
			public const int options = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int play = 2131034113;
			
			// aapt resource value: 0x7f05000a
			public const int restart = 2131034122;
			
			// aapt resource value: 0x7f050008
			public const int save = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int savesuccess = 2131034121;
			
			// aapt resource value: 0x7f05000c
			public const int yes = 2131034124;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
